// Catalog of technologies and topics offered in onboarding / profile.
// Users can always add anything that isn't here — this is a starting point, not a whitelist.

export interface CatalogGroup {
  group: string;
  items: string[];
}

export const TECH_CATALOG: CatalogGroup[] = [
  {
    group: 'Linguagens',
    items: [
      'Python',
      'JavaScript',
      'TypeScript',
      'Java',
      'Kotlin',
      'C#',
      'Go',
      'Rust',
      'C',
      'C++',
      'Ruby',
      'PHP',
      'Swift',
      'Objective-C',
      'Dart',
      'Scala',
      'Elixir',
      'Erlang',
      'Clojure',
      'Haskell',
      'OCaml',
      'F#',
      'Zig',
      'Nim',
      'Julia',
      'R',
      'Lua',
      'Perl',
      'Bash',
      'PowerShell',
      'SQL',
      'Solidity',
      'Assembly',
      'WebAssembly',
      'Mojo',
      'Gleam',
    ],
  },
  {
    group: 'Frontend',
    items: [
      'React',
      'Next.js',
      'Vue',
      'Nuxt',
      'Angular',
      'Svelte',
      'SvelteKit',
      'SolidJS',
      'Qwik',
      'Astro',
      'Remix',
      'React Router',
      'HTMX',
      'Alpine.js',
      'Tailwind CSS',
      'CSS',
      'Sass',
      'shadcn/ui',
      'Radix UI',
      'Storybook',
      'Vite',
      'Webpack',
      'Turbopack',
      'esbuild',
      'Redux',
      'Zustand',
      'TanStack Query',
      'Three.js',
      'D3.js',
      'WebGL',
      'WebGPU',
    ],
  },
  {
    group: 'Backend',
    items: [
      'Node.js',
      'Deno',
      'Bun',
      'Express',
      'Fastify',
      'NestJS',
      'Hono',
      'FastAPI',
      'Django',
      'Flask',
      'Spring Boot',
      'Quarkus',
      'ASP.NET Core',
      'Ruby on Rails',
      'Laravel',
      'Phoenix',
      'Gin',
      'Echo',
      'Axum',
      'Actix',
      'GraphQL',
      'gRPC',
      'tRPC',
      'REST',
      'WebSockets',
      'OpenAPI',
      'Microservices',
      'Event-driven',
      'Serverless',
    ],
  },
  {
    group: 'Mobile & Desktop',
    items: [
      'React Native',
      'Expo',
      'Flutter',
      'SwiftUI',
      'Jetpack Compose',
      'Kotlin Multiplatform',
      'Ionic',
      'Capacitor',
      'Electron',
      'Tauri',
      '.NET MAUI',
    ],
  },
  {
    group: 'Bancos de dados',
    items: [
      'PostgreSQL',
      'MySQL',
      'MariaDB',
      'SQLite',
      'SQL Server',
      'Oracle',
      'MongoDB',
      'Redis',
      'Valkey',
      'Cassandra',
      'ScyllaDB',
      'DynamoDB',
      'Firestore',
      'Supabase',
      'Neon',
      'PlanetScale',
      'CockroachDB',
      'ClickHouse',
      'DuckDB',
      'Elasticsearch',
      'OpenSearch',
      'Neo4j',
      'pgvector',
      'Qdrant',
      'Weaviate',
      'Pinecone',
      'Milvus',
      'Chroma',
      'Prisma',
      'Drizzle',
      'SQLAlchemy',
      'TypeORM',
    ],
  },
  {
    group: 'IA & Machine Learning',
    items: [
      'LLMs',
      'Claude API',
      'OpenAI API',
      'Gemini API',
      'Ollama',
      'llama.cpp',
      'vLLM',
      'Hugging Face',
      'Transformers',
      'PyTorch',
      'TensorFlow',
      'JAX',
      'scikit-learn',
      'LangChain',
      'LangGraph',
      'LlamaIndex',
      'DSPy',
      'Claude Agent SDK',
      'MCP',
      'RAG',
      'Embeddings',
      'Fine-tuning',
      'LoRA',
      'Prompt engineering',
      'AI Agents',
      'Tool calling',
      'Evals',
      'Computer vision',
      'Speech / ASR',
      'Diffusion models',
      'MLOps',
      'MLflow',
      'Weights & Biases',
    ],
  },
  {
    group: 'Dados',
    items: [
      'Pandas',
      'Polars',
      'NumPy',
      'Apache Spark',
      'Kafka',
      'Flink',
      'Airflow',
      'dbt',
      'Dagster',
      'Snowflake',
      'BigQuery',
      'Databricks',
      'Jupyter',
      'Power BI',
      'ETL',
    ],
  },
  {
    group: 'DevOps & Cloud',
    items: [
      'Docker',
      'Kubernetes',
      'Helm',
      'Terraform',
      'OpenTofu',
      'Pulumi',
      'Ansible',
      'AWS',
      'Google Cloud',
      'Azure',
      'Cloudflare',
      'Vercel',
      'Fly.io',
      'Railway',
      'GitHub Actions',
      'GitLab CI',
      'Jenkins',
      'ArgoCD',
      'Nginx',
      'Caddy',
      'Linux',
      'Prometheus',
      'Grafana',
      'OpenTelemetry',
      'Datadog',
      'Sentry',
      'Istio',
    ],
  },
  {
    group: 'Segurança',
    items: [
      'OAuth / OIDC',
      'JWT',
      'OWASP',
      'AppSec',
      'Pentest',
      'Criptografia',
      'Zero Trust',
      'Supply chain security',
      'SAST/DAST',
      'Keycloak',
    ],
  },
  {
    group: 'Testes & Qualidade',
    items: [
      'Jest',
      'Vitest',
      'Playwright',
      'Cypress',
      'pytest',
      'JUnit',
      'Testing Library',
      'k6',
      'TDD',
      'ESLint',
      'Biome',
      'Prettier',
    ],
  },
  {
    group: 'Arquitetura & Fundamentos',
    items: [
      'Estruturas de dados',
      'Algoritmos',
      'System design',
      'Sistemas distribuídos',
      'Design patterns',
      'Clean Architecture',
      'DDD',
      'CQRS',
      'Event sourcing',
      'Concorrência',
      'Redes',
      'Sistemas operacionais',
      'Compiladores',
      'Performance',
      'Caching',
      'Filas / mensageria',
    ],
  },
  {
    group: 'Ferramentas',
    items: [
      'Git',
      'GitHub',
      'VS Code',
      'Neovim',
      'JetBrains',
      'Claude Code',
      'Cursor',
      'Figma',
      'Postman',
      'Obsidian',
      'Nix',
      'tmux',
    ],
  },
  {
    group: 'Web3 & Outros',
    items: [
      'Ethereum',
      'Solana',
      'Smart contracts',
      'IoT',
      'Embedded',
      'Arduino',
      'Raspberry Pi',
      'Game dev',
      'Unity',
      'Unreal',
      'Godot',
      'AR/VR',
    ],
  },
];

export const TOPIC_CATALOG: CatalogGroup[] = [
  {
    group: 'IA',
    items: [
      'AI Agents',
      'RAG',
      'Local AI',
      'LLM releases',
      'MCP',
      'AI coding tools',
      'Evals',
      'Fine-tuning',
      'Multimodal',
      'AI safety',
      'Pesquisa em IA',
    ],
  },
  {
    group: 'Engenharia',
    items: [
      'Backend',
      'Frontend',
      'Full-stack',
      'Mobile',
      'Arquitetura',
      'Performance',
      'Developer experience',
      'Open Source',
      'Linguagens novas',
      'WebAssembly',
    ],
  },
  {
    group: 'Infra & Dados',
    items: [
      'DevOps',
      'Cloud',
      'Kubernetes',
      'Observabilidade',
      'Bancos de dados',
      'Engenharia de dados',
      'Edge computing',
      'Platform engineering',
    ],
  },
  {
    group: 'Segurança',
    items: ['Segurança', 'Vulnerabilidades (CVEs)', 'Supply chain', 'Privacidade'],
  },
  {
    group: 'Carreira & Mercado',
    items: ['Carreira', 'Startups', 'Produto', 'Liderança técnica', 'Freelance'],
  },
];

export const ROLE_OPTIONS = [
  'Engenheiro de backend',
  'Engenheiro de frontend',
  'Full-stack',
  'Engenheiro de IA',
  'Engenheiro de ML',
  'Engenheiro de dados',
  'Engenheiro de plataforma',
  'DevOps / SRE',
  'Engenheiro mobile',
  'Engenheiro de segurança',
  'Arquiteto de software',
  'Tech lead',
  'Pesquisador',
  'Indie hacker / founder',
];

export const BUILDING_OPTIONS = [
  'Um assistente de IA',
  'Um agente autônomo',
  'Uma API',
  'Um app web',
  'Um app mobile',
  'Um SaaS',
  'Ferramentas internas',
  'Uma CLI',
  'Um pipeline de dados',
  'Infraestrutura / plataforma',
  'Um jogo',
  'Contribuições open source',
  'Nada ainda',
];
